/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader?{\"esModule\":false}!./userstyle.css";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css
};